spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_tutorial
    username: blog_tutorial_usr
    password: blog_tutorial_pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
